#!/bin/bash

set -e

if [[ "$1" =~ ^-.* ]]; then
	ip="${2:-virtuo.local}"
else
	ip="${1:-virtuo.local}"
fi

if ! ping -c 1 $ip > /dev/null 2> /dev/null; then
	echo "Host $ip not found"
	exit 1
fi

echo "Starting sync ..."

ssh pi@"${ip}" "mkdir -p /home/pi/virtuo"
rsync -P -a --delete -e ssh --exclude-from=".rsync-exclude" . pi@"${ip}":/home/pi/virtuo
ssh pi@"${ip}" "cd ~/virtuo && mv rpi_config.yml config.yml && mv rpi_Pipfile Pipfile && mv rpi_run run"

echo "Done"
