camera:
  left: 0
  right: 0
  width: 1920
  height: 1080
  photo_delay: 5
  focus: 10
  black_threshold: 110
audio:
  voices:
    - name: Male 1
      voice_name: en-GB-Standard-D
      language: en-GB
      gender: male
      offline: false
    - name: Female 1
      voice_name: en-GB-Standard-C
      language: en-GB
      gender: female
      offline: false
    - name: Male 2 (offline)
      voice_name: ...
      gender: male
      offline: true
    - name: Female 2 (offline)
      voice_name: ...
      gender: female
      offline: true
web:
  host: 0.0.0.0
  port: 80
book_location: /home/pi/books