camera:
  left: 0
  right: 2
  width: 2304
  height: 1296
  photo_delay: 2
  init_time: 5
  focus:
    left: 60
    right: 50
  crop:
    left:
      top: 350
      right: 1
      bottom: 305
      left: 130
    right:
      top: 300
      right: 130
      bottom: 355
      left: 1
audio:
  voices:
    - name: Female 1
      voice_name: en-GB-Standard-C
      language: en-GB
      offline: false
    - name: Female 2 (offline)
      voice_name: en-GB
      language: en-GB
      offline: true
    - name: Male 1
      voice_name: en-GB-Standard-D
      language: en-GB
      offline: false
    - name: Female 3 (offline)
      voice_name: en-US
      language: en-US
      offline: true
web:
  host: 0.0.0.0
  port: 80
book_location: /home/pi/books
debug_location: /home/pi/virtuo_debug