camera:
  left: 0
  right: 0
  width: 1920
  height: 1080
  photo_delay: 1
  focus: 20
  black_threshold: 110
audio:
  voices:
    google_tts:
      - name: Male 1
        voice_name: en-GB-Standard-D
        language: en-GB
      - name: Female 1
        voice_name: en-GB-Standard-C
        language: en-GB
    google_default: 0
    google_speaking_rate: 1
book_location: /home/pi/books