camera:
  left: 0
  right: 2
  width: 2304
  height: 1296
  photo_delay: 2
  init_time: 5
  focus:
    left: 45
    right: 40
  crop:
    left:
      top: 370
      right: 75
      bottom: 250
      left: 0
    right:
      top: 400
      right: 0
      bottom: 200
      left: 0
audio:
  voices:
    - name: Female 1
      voice_name: en-GB-Standard-C
      language: en-GB
      offline: false
    - name: Female 2 (offline)
      voice_name: en-GB
      language: en-GB
      offline: true
    - name: Male 1
      voice_name: en-GB-Standard-D
      language: en-GB
      offline: false
    - name: Female 3 (offline)
      voice_name: en-US
      language: en-US
      offline: true
web:
  host: 0.0.0.0
  port: 80
book_location: /home/pi/books